name: ESMF Build and Cache

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: mpicc
      FC: mpifort
      CXX: mpicxx
      CPPFLAGS: "-I/usr/include -I/usr/local/include"
    steps:
     - uses: actions/checkout@v2
     - name: Cache ESMF
       id: cache-esmf
       uses: actions/cache@v2
       with:
         path: ESMF
         key: ${{ runner.os }}-ESMF
     - name: ESMF build
       if: steps.cache-esmf.outputs.cache-hit != 'true'
       run: |
         sudo apt-get install gfortran wget openmpi-bin libopenmpi-dev
         wget https://github.com/esmf-org/esmf/archive/ESMF_8_1_0_beta_snapshot_25.tar.gz
         tar -xzvf ESMF_8_1_0_beta_snapshot_25.tar.gz
         cd esmf-ESMF_8_1_0_beta_snapshot_25
         export ESMF_DIR=`pwd`
         make ESMF_COMM=openmpi ESMF_YAMLCPP="internal" ESMF_INSTALL_PREFIX=../ESMF
         make install